In [2]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10) : my_arr2 = my_arr*2
%time for _ in range(10) : my_list2 = [x*2 for x in my_list]

CPU times: total: 15.6 ms
Wall time: 17 ms
CPU times: total: 609 ms
Wall time: 615 ms


In [3]:
data = np.random.rand(2,3)
data

array([[0.11522479, 0.81026608, 0.81624681],
       [0.18296781, 0.49709588, 0.51848395]])

In [4]:
data1 = np.random.randn(2,3)
data1

array([[ 1.35741871,  0.36610669, -0.67126359],
       [ 0.31188187, -1.3807481 ,  1.90309718]])

In [5]:
data2 = np.random.randint(1,5,size=(2,5))
data2

array([[3, 1, 3, 4, 2],
       [3, 4, 1, 2, 1]])

In [24]:
data3 = [1,2,3,4,5]
type(data3)

arr3 = np.array(data3,dtype=np.int64)
arr3



[1, 2, 3, 4, 5]

In [22]:
data = [1,2,3,'4',1212]
arra = np.array(data)
arra

array(['1', '2', '3', '4', '1212'], dtype='<U11')

In [28]:
data1 = ['1','2','3','4','1212']
arra1 = np.array(data1)
arra1.dtype

dtype('<U4')

In [29]:
data2 = [[1,2,3],[2,4,5]]
arra2 = np.array(data2)
arra2

array([[1, 2, 3],
       [2, 4, 5]])

In [43]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [48]:
x = arr.astype('int64')
arr.dtype

dtype('int32')

In [51]:
arr = np.array([-1.12,-2.23,-11.241])
q =arr.astype(np.string_)
q.dtype

dtype('S32')