In [17]:
import numpy as np

my_arr = np.arange(1000000)
my_list = list(range(1000000))

%time for _ in range(10) : my_arr2 = my_arr*2
%time for _ in range(10) : my_list2 = [x*2 for x in my_list]

CPU times: total: 15.6 ms
Wall time: 14 ms
CPU times: total: 656 ms
Wall time: 733 ms


In [18]:
data = np.random.rand(2,3)
data

array([[0.2992117 , 0.45260093, 0.95952539],
       [0.46424925, 0.45885164, 0.50181479]])

In [19]:
data1 = np.random.randn(2,3)
data1

array([[ 0.47034179,  1.37765468,  1.15172361],
       [-0.98880031, -0.95732885,  0.76784607]])

In [20]:
data2 = np.random.randint(1,5,size=(2,5))
data2

array([[2, 4, 4, 3, 3],
       [3, 4, 2, 4, 4]])

In [21]:
data3 = [1,2,3,4,5]
type(data3)

arr3 = np.array(data3,dtype=np.int64)
arr3



array([1, 2, 3, 4, 5], dtype=int64)

In [22]:
data = [1,2,3,'4',1212]
arra = np.array(data)
arra

array(['1', '2', '3', '4', '1212'], dtype='<U11')

In [23]:
data1 = ['1','2','3','4','1212']
arra1 = np.array(data1)
arra1.dtype

dtype('<U4')

In [24]:
data2 = [[1,2,3],[2,4,5]]
arra2 = np.array(data2)
arra2

array([[1, 2, 3],
       [2, 4, 5]])

In [25]:
arr = np.array([1,2,3,4,5])
arr.dtype

dtype('int32')

In [26]:
x = arr.astype('int64')
arr.dtype

dtype('int32')

In [27]:
arr = np.array([-1.12,-2.23,-11.241])
q =arr.astype(np.string_)
q.dtype

dtype('S32')

In [28]:
arra = np.arange(10)
arra

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
type(arra)

numpy.ndarray

In [29]:
arra[2:5] 

array([2, 3, 4])

In [30]:
arra[2:5]=12
arra

array([ 0,  1, 12, 12, 12,  5,  6,  7,  8,  9])

In [31]:
arra[:]

array([ 0,  1, 12, 12, 12,  5,  6,  7,  8,  9])

In [36]:
arr1 = arra[2:6].copy()
arr1

array([12, 12, 12,  5])

In [37]:
arr1[:] = 13
arr1

array([13, 13, 13, 13])

In [38]:
arra

array([ 0,  1, 12, 12, 12,  5,  6,  7,  8,  9])

In [45]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
arr2d[:2,:1]

array([[1],
       [4]])

In [49]:
arr2d[2,2]

9